import { ProviderConfig, UserSettings } from '../types';

export const DEFAULT_PROVIDERS: ProviderConfig[] = [
  {
    id: 'deepseek',
    name: 'DeepSeek (官方)',
    baseUrl: 'https://api.deepseek.com/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://platform.deepseek.com/api_keys',
    icon: '⚡',
  },
  {
    id: 'sensenova',
    name: 'SenseNova (商汤日日新)',
    baseUrl: 'https://token.sensenova.cn/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://platform.sensenova.cn/',
    icon: '🔮',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow (硅基流动)',
    baseUrl: 'https://api.siliconflow.cn/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://cloud.siliconflow.cn/account/ak',
    icon: '🌊',
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://aistudio.google.com/app/apikey',
    icon: '✨',
  },
  {
    id: 'openai',
    name: 'OpenAI (官方)',
    baseUrl: 'https://api.openai.com/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://platform.openai.com/api-keys',
    icon: '🤖',
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://platform.moonshot.cn/console/api-keys',
    icon: '🌙',
  },
  {
    id: 'zhipu',
    name: '智谱 BigModel (GLM)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    icon: '🧠',
  },
  {
    id: 'ollama',
    name: 'Ollama (本地模型)',
    baseUrl: 'http://localhost:11434/v1',
    apiKey: 'ollama',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://ollama.com',
    icon: '🦙',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKey: '',
    enabled: true,
    models: [],
    remoteModels: [],
    selectedModel: '',
    fallbackModel: '',
    docUrl: 'https://openrouter.ai/keys',
    icon: '🌐',
  },
];

export const DEFAULT_SETTINGS: UserSettings = {
  providers: DEFAULT_PROVIDERS,
  activeProviderId: 'deepseek',
  activeModel: '',
  enableFallback: true,
  autoFetch: true,
  shortcutToggle: 'Alt+S',
  theme: 'dark',
};
